import { useMemo, useState } from "react";
import { X, Phone, Copy, Check, FileText, Shield, Car, Building2 } from "lucide-react";
import { VEHICLE_RISK } from "@/lib/risk";

interface Props {
  onClose: () => void;
  defaultVehicleIdx: number;
  locationLabel: string;
}

const STEPS = [
  {
    icon: Phone,
    title: "Call Toronto Police",
    body: "Dial 416-808-2222 (non-emergency) or 911 if the theft is in progress. Get an event/occurrence number — your insurer will require it.",
  },
  {
    icon: Building2,
    title: "Notify your insurer within 24 hours",
    body: "Most policies require prompt reporting. Have your policy number, the police occurrence number, and the time/location ready.",
  },
  {
    icon: Car,
    title: "Report to ICBC-equivalent / MTO if plates were taken",
    body: "In Ontario, contact ServiceOntario to flag the plates and VIN. This prevents the vehicle from being re-registered fraudulently.",
  },
  {
    icon: Shield,
    title: "Lock your credit & re-key the spare",
    body: "If documents (insurance pink slip, ownership) were inside, place a fraud alert with Equifax (1-800-465-7166) and TransUnion (1-800-663-9980).",
  },
  {
    icon: FileText,
    title: "Submit your claim package",
    body: "Send the police occurrence number, photos of where the car was parked, the keys you still possess, ownership docs, and a list of personal items lost.",
  },
];

export default function ClaimGuide({ onClose, defaultVehicleIdx, locationLabel }: Props) {
  const [vehicleIdx, setVehicleIdx] = useState(defaultVehicleIdx);
  const [policy, setPolicy] = useState("");
  const [occurrence, setOccurrence] = useState("");
  const [when, setWhen] = useState(() => {
    const d = new Date();
    d.setMinutes(d.getMinutes() - d.getTimezoneOffset());
    return d.toISOString().slice(0, 16);
  });
  const [vin, setVin] = useState("");
  const [plate, setPlate] = useState("");
  const [copied, setCopied] = useState(false);

  const v = VEHICLE_RISK[vehicleIdx];
  const summary = useMemo(() => {
    const lines = [
      "VEHICLE THEFT INSURANCE CLAIM SUMMARY",
      "",
      `Vehicle: ${v.model ? `${v.make} ${v.model}` : v.make}`,
      `Plate: ${plate || "—"}`,
      `VIN: ${vin || "—"}`,
      `Date/time of theft: ${when ? new Date(when).toLocaleString() : "—"}`,
      `Last known location: ${locationLabel}`,
      `Police occurrence #: ${occurrence || "—"}`,
      `Policy #: ${policy || "—"}`,
      "",
      "Actions taken:",
      "  [ ] Police report filed (Toronto Police 416-808-2222)",
      "  [ ] Insurer notified",
      "  [ ] ServiceOntario notified (plates/VIN flagged)",
      "  [ ] Credit bureaus alerted (if documents lost)",
      "  [ ] Photos of parking location attached",
      "",
      "Generated by ParkSafe Toronto",
    ];
    return lines.join("\n");
  }, [v, plate, vin, when, locationLabel, occurrence, policy]);

  async function copy() {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      /* ignore */
    }
  }

  return (
    <>
      <div
        className="absolute inset-0 z-[1300] bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      <div className="absolute left-1/2 top-1/2 z-[1400] max-h-[90vh] w-[94%] max-w-lg -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-2xl border border-border bg-card p-5 shadow-2xl">
        <div className="mb-4 flex items-start justify-between">
          <div>
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Recovery & insurance
            </div>
            <h2 className="text-base font-semibold">Vehicle theft claim assistant</h2>
            <p className="mt-1 text-xs text-muted-foreground">
              A guided checklist plus a clean summary you can paste into your insurer's claim form
              or text to a family member.
            </p>
          </div>
          <button
            onClick={onClose}
            className="rounded-full p-2 text-muted-foreground hover:bg-muted hover:text-foreground"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <ol className="space-y-2">
          {STEPS.map((s, i) => {
            const Icon = s.icon;
            return (
              <li
                key={i}
                className="flex gap-3 rounded-xl border border-border bg-background/40 p-3"
              >
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary/15 text-primary">
                  <Icon className="h-4 w-4" />
                </div>
                <div>
                  <div className="text-sm font-medium">
                    {i + 1}. {s.title}
                  </div>
                  <p className="mt-0.5 text-xs text-muted-foreground">{s.body}</p>
                </div>
              </li>
            );
          })}
        </ol>

        <div className="mt-5 grid grid-cols-2 gap-2">
          <Field label="Vehicle">
            <select
              value={vehicleIdx}
              onChange={(e) => setVehicleIdx(Number(e.target.value))}
              className="w-full rounded-lg border border-border bg-input px-2 py-2 text-xs focus:border-ring focus:outline-none"
            >
              {VEHICLE_RISK.map((veh, i) => (
                <option key={i} value={i}>
                  {veh.model ? `${veh.make} ${veh.model}` : veh.make}
                </option>
              ))}
            </select>
          </Field>
          <Field label="When">
            <input
              type="datetime-local"
              value={when}
              onChange={(e) => setWhen(e.target.value)}
              className="w-full rounded-lg border border-border bg-input px-2 py-2 text-xs focus:border-ring focus:outline-none"
            />
          </Field>
          <Field label="Plate">
            <input
              value={plate}
              maxLength={10}
              onChange={(e) => setPlate(e.target.value.toUpperCase())}
              placeholder="ABCD123"
              className="w-full rounded-lg border border-border bg-input px-2 py-2 text-xs focus:border-ring focus:outline-none"
            />
          </Field>
          <Field label="VIN">
            <input
              value={vin}
              maxLength={17}
              onChange={(e) => setVin(e.target.value.toUpperCase())}
              placeholder="17-char VIN"
              className="w-full rounded-lg border border-border bg-input px-2 py-2 text-xs focus:border-ring focus:outline-none"
            />
          </Field>
          <Field label="Police occurrence #">
            <input
              value={occurrence}
              maxLength={32}
              onChange={(e) => setOccurrence(e.target.value)}
              className="w-full rounded-lg border border-border bg-input px-2 py-2 text-xs focus:border-ring focus:outline-none"
            />
          </Field>
          <Field label="Policy #">
            <input
              value={policy}
              maxLength={32}
              onChange={(e) => setPolicy(e.target.value)}
              className="w-full rounded-lg border border-border bg-input px-2 py-2 text-xs focus:border-ring focus:outline-none"
            />
          </Field>
        </div>

        <div className="mt-4 rounded-xl border border-border bg-background/40 p-3">
          <div className="mb-2 flex items-center justify-between">
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Claim summary
            </div>
            <button
              onClick={copy}
              className="flex items-center gap-1.5 rounded-lg bg-primary px-2.5 py-1 text-[11px] font-medium text-primary-foreground hover:opacity-90"
            >
              {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
              {copied ? "Copied" : "Copy"}
            </button>
          </div>
          <pre className="whitespace-pre-wrap break-words text-[11px] leading-relaxed text-muted-foreground">
            {summary}
          </pre>
        </div>

        <p className="mt-3 text-[10px] leading-relaxed text-muted-foreground">
          ParkSafe is not your insurer. Always confirm coverage and required documents directly with
          your insurance company. For active emergencies call 911.
        </p>
      </div>
    </>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <div className="mb-1 text-[9px] uppercase tracking-wider text-muted-foreground">
        {label}
      </div>
      {children}
    </label>
  );
}
